dbt_example:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: projeto-dbt-479500
      dataset: dbt
      threads: 4
      keyfile: /home/daniel/dbt-course/projeto-dbt-479500-a3e67a36f72b.json