version: 2

#posso colocar mais de uma source nesses sources
sources:
  - name: finance
    description: "dados de finance" # Corrigido de 'descripition'
    schema: dataset_financial
    loader: bigquery
    loaded_at_field: loaded_at ##criar uma coluna de controle de carga de dados (última vez que os dados foram carregados)
    meta: #metadados adicionais sobre a source
      owner: "daniel"
      last_updated: "2024-06-10" ##último update desta source
      team: "data-analytics"
    freshness: #configuração de frescor dos dados
      warn_after: 
        count: 12
        period: hour #se os dados não forem atualizados em 12 horas, emitir um aviso
      error_after:
        count: 24
        period: hour #se os dados não forem atualizados em 24 horas, emitir um erro
    
    # Tables agora é uma lista (por isso o traço abaixo)
    tables: 
      - name: financial
        description: "Dados brutos do sistema financeiro da empresa" # Corrigido de 'descripition'
        
        # Colunas é uma lista de objetos, cada um com 'name', 'description' e 'tests'
        columns:
          - name: Segment
            description: "Segmento de mercado"
          - name: Country
            description: "País da venda"
          - name: Product 
            description: "Produto vendido"
          - name: Discount Band 
            description: "Faixa de desconto aplicada"
          - name: Units Sold 
            description: "Número de unidades vendidas"
          - name: Manufacturing Price 
            description: "Preço de fabricação do produto"
          - name: Sale Price 
            description: "Preço de venda do produto"
          - name: Gross Sales 
            description: "Valor bruto das vendas"
          - name: Discounts 
            description: "Valor dos descontos aplicados"
          - name: Sales 
            description: "Valor líquido das vendas"
          - name: COGS 
            description: "Custo dos produtos vendidos"
          - name: Profit 
            description: "Lucro obtido"
          - name: Date
            description: "Data da venda"
            #exemplo de caso em que quero realizar um teste para um pk abaixo
            tests:
              - not_null
              - unique
          - name: Month Number
            description: "Número do mês da venda"
          - name: Month Name 
            description: "Nome do mês da venda"
          - name: Year
            description: "Ano da venda"