name: 'dbt_example'
version: '1.0.0'


profile: 'dbt_example'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


#variables examples

vars:
  ambiente: 'dev'
  data_minima: '2022-01-01'
  schema_nome: 'desenvolvimento_schema'

models:
  dbt_example:
    staging:
      schema: staging
      materialized: table
      tags: ['staging']
    
    intermediate:
      materialized: ephemeral #views criam um objeto físico de banco de dados (uma "visualização") que é recriado a cada execução, enquanto ephemeral não cria nenhum objeto físico
      tags: ['intermediate']

    marts:
      schema: marts
      materialized: table    
      tags: ['marts']

seeds:
  +schema: seeds
  materialized: seed
  tags: ['seeds']

# debug: true

snapshots:
  +schema: snapshots
  +tags: ['snapshots']
  schema: snapshots